name: Build and Sign Image (Docker Hub)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write   # REQUIRED for keyless cosign

jobs:
  build-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push images
        run: |
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/cosign-test:${{ github.sha }}
          cd Part7/cosign-test
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "pushed cosign-test to tag $IMAGE"

          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/unsigned-test:${{ github.sha }}
          cd Part7/unsigned-test
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "pushed unsigned-test to tag $IMAGE"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image with cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_YES: "true"
        run: |
          cosign sign $DIGEST
