name: AllergyLab CI

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build images
      run: |
        cd Part7a
        APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-app:${{ github.sha }}
        echo APP_IMAGE=$APP_IMAGE >> $GITHUB_ENV
        docker build -t $APP_IMAGE ./app
        DB_LOADER_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-db-loader:${{ github.sha }}
        echo DB_LOADER_IMAGE=$DB_LOADER_IMAGE >> $GITHUB_ENV
        docker build -t $DB_LOADER_IMAGE ./db-loader
        EMAIL_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-email:${{ github.sha }}
        echo EMAIL_IMAGE=$EMAIL_IMAGE >> $GITHUB_ENV
        docker build -t $EMAIL_IMAGE ./email
    - name: Log in to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push images to DockerHub
      run: |
        docker push $APP_IMAGE
        docker push $DB_LOADER_IMAGE
        docker push $EMAIL_IMAGE
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: '**PLACEHOLDER** Deploy to Kubernetes'
      run: echo Placeholder for Deployment
    - name: Run containers
      run: |
        APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-app:${{ github.sha }}
        docker run -d $APP_IMAGE
        DB_LOADER_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-db-loader:${{ github.sha }}
        docker run -d $DB_LOADER_IMAGE
        EMAIL_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-email:${{ github.sha }}
        docker run -d $EMAIL_IMAGE