name: AllergyLab CI

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build images
      run: |
        cd Part7a
        APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-app:${{ github.sha }}
        echo APP_IMAGE=$APP_IMAGE >> $GITHUB_ENV
        docker build -t $APP_IMAGE ./app
        DB_LOADER_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-db-loader:${{ github.sha }}
        echo DB_LOADER_IMAGE=$DB_LOADER_IMAGE >> $GITHUB_ENV
        docker build -t $DB_LOADER_IMAGE ./db-loader
        EMAIL_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-email:${{ github.sha }}
        echo EMAIL_IMAGE=$EMAIL_IMAGE >> $GITHUB_ENV
        docker build -t $EMAIL_IMAGE ./email
    - name: Log in to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push images to DockerHub
      run: |
        echo Pushing $APP_IMAGE
        docker push $APP_IMAGE
        APP_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $APP_IMAGE)
        echo APP_DIGEST=$APP_DIGEST >> $GITHUB_ENV
        echo Pushing $DB_LOADER_IMAGE
        docker push $DB_LOADER_IMAGE
        DB_LOADER_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $DB_LOADER_IMAGE)
        echo DB_LOADER_DIGEST=$DB_LOADER_DIGEST >> $GITHUB_ENV
        echo Pushing $EMAIL_IMAGE
        docker push $EMAIL_IMAGE
        EMAIL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $EMAIL_IMAGE)
        echo EMAIL_DIGEST=$EMAIL_DIGEST >> $GITHUB_ENV
    - name: Install cosign
      uses: sigstore/cosign-installer@v3
    - name: Sign images
      env:
        COSIGN_EXPERIMENTAL: "true"
        COSIGN_YES: "true"
      run: |
        cosign sign $APP_DIGEST
        cosign sign $DB_LOADER_DIGEST
        cosign sign $EMAIL_DIGEST
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: '**PLACEHOLDER** Deploy to Kubernetes'
      run: echo Placeholder for Deployment
    - name: Run containers
      run: |
        APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-app:${{ github.sha }}
        docker run -d $APP_IMAGE
        DB_LOADER_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-db-loader:${{ github.sha }}
        docker run -d $DB_LOADER_IMAGE
        EMAIL_IMAGE=${{ secrets.DOCKER_USERNAME }}/al-email:${{ github.sha }}
        docker run -d $EMAIL_IMAGE